[project]
name = "c2s-desafio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.5.1",
    "sqlalchemy>=2.0.41",
]
